name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Run Oxlint and Oxfmt
        run: bun lint

      - name: Run Prettier
        run: bun prettier

      - name: Run tsc
        run: bun tsc

      - name: Run Stylelint
        run: bun stylelint

      - name: Run package-format
        run: bun package-format

      - name: Run package-lint-semver-ranges
        run: bun package-lint-semver-ranges

      - name: Run knip
        run: bun knip
